// ----------------------------------------------------------------------------
// VGDD Main Skeleton - Harmony version
// This program is the starting point to build a VGDD-enabled GOL Application
// ----------------------------------------------------------------------------
// FileName:          vgdd_main.c
// Generated by:      VGDD [VGDDVERSION] MPLAB X Wizard [COPYRIGHT]
// Dependencies:      vgdd_main.h, [PROJECTFILENAME_SCREENSC], [PROJECTFILENAME_SCREENSH]
// Compiler:          [COMPILER]
// Development Board: [DEVBOARD]
// Expansion Board:   [EXPANSIONBOARD]
// Display Board:     [DISPLAYBOARD] - Orientation: [DISP_ORIENTATION] degrees
// Company:           VirtualFab, with adapted parts from Microchip Technology Incorporated
//
// ----------------------------------------------------------------------------
// VirtualFab Software License Agreement:
// ----------------------------------------------------------------------------
// [COPYRIGHT] - All rights reserved.
// Redistribution and use in source and binary forms, with or without modification,
// are permitted provided that the following conditions are met:
// Redistributions of source code must retain the above and following copyright notices,
// this list of conditions and the following disclaimer.
// Neither the name of Fabio Violino or VirtualFab may be used to endorse or promote 
// products derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR “AS IS” AND ANY EXPRESS OR IMPLIED WARRANTIES,
// INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
// FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
// EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT 
// OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS 
// INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, 
// STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY 
// OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
// ----------------------------------------------------------------------------
// Microchip's Software License Agreement:
// ----------------------------------------------------------------------------
// Copyright © 2013 Microchip Technology Inc.  All rights reserved.
// Microchip licenses to you the right to use, modify, copy and distribute
// Software only when embedded on a Microchip microcontroller or digital
// signal controller, which is integrated into your product or third party
// product (pursuant to the sublicense terms in the accompanying license
// agreement).
//
// You should refer to the license agreement accompanying this Software
// for additional information regarding your rights and obligations.
//
// SOFTWARE AND DOCUMENTATION ARE PROVIDED “AS IS” WITHOUT WARRANTY OF ANY
// KIND, EITHER EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION, ANY WARRANTY
// OF MERCHANTABILITY, TITLE, NON-INFRINGEMENT AND FITNESS FOR A PARTICULAR
// PURPOSE. IN NO EVENT SHALL MICROCHIP OR ITS LICENSORS BE LIABLE OR
// OBLIGATED UNDER CONTRACT, NEGLIGENCE, STRICT LIABILITY, CONTRIBUTION,
// BREACH OF WARRANTY, OR OTHER LEGAL EQUITABLE THEORY ANY DIRECT OR INDIRECT
// DAMAGES OR EXPENSES INCLUDING BUT NOT LIMITED TO ANY INCIDENTAL, SPECIAL,
// INDIRECT, PUNITIVE OR CONSEQUENTIAL DAMAGES, LOST PROFITS OR LOST DATA,
// COST OF PROCUREMENT OF SUBSTITUTE GOODS, TECHNOLOGY, SERVICES, OR ANY
// CLAIMS BY THIRD PARTIES (INCLUDING BUT NOT LIMITED TO ANY DEFENSE THEREOF),
// OR OTHER SIMILAR COSTS.
//
// Author               Date        Comment
//
// VirtualFab        2012/01/29     First MPLAB X Wizard implementation 
// VirtualFab        2012/10/18     VGDD 4.1 Release
// VirtualFab        2014/03/30     Harmony Version
// VirtualFab        2014/07/04     VGDD 8.0 Release
// ----------------------------------------------------------------------------
#include "vgdd_main.h"

// --------------------------------------------------------------------
//                            LOCAL PROTOTYPES
// --------------------------------------------------------------------
#define WAIT_UNTIL_FINISH(x)    while(!x)

// --------------------------------------------------------------------
//                             FONTS USED
// --------------------------------------------------------------------
//extern const GFX_RESOURCE_FONT FONTDEFAULT; // default GOL font

// MainHead
// <editor-fold defaultstate="collapsed" desc="Generated Code">
// VGDD_MPLABX_WIZARD_START_SECTION: MainHead *** DO NOT DELETE THIS LINE! ***
// VGDD_MPLABX_WIZARD_END_SECTION *** DO NOT DELETE THIS LINE! ***
// </editor-fold>

// --------------------------------------------------------------------
//                       GLOBAL VARIABLES FOR APPLICATION
// --------------------------------------------------------------------
volatile SCREEN_STATES screenState=SCREENSTATE_INIT; // current state of state machine
#if defined(USE_BITMAP_SD) || defined(USB_SUPPORT_HOST)
uint8_t usbErrorCode; // USB error
#endif

// --------------------------------------------------------------------
//                                  MAIN
// --------------------------------------------------------------------

int main(void) {
    /*Call the SYS Init routine. App init routine gets called from this*/
    SYS_Initialize(NULL);

// <editor-fold defaultstate="collapsed" desc="Generated Code">
// VGDD_MPLABX_WIZARD_START_SECTION: MainBeforeLoop *** DO NOT DELETE THIS LINE! ***
// VGDD_MPLABX_WIZARD_END_SECTION *** DO NOT DELETE THIS LINE! ***
// </editor-fold>

    while (true) {
// <editor-fold defaultstate="collapsed" desc="Generated Code">
// VGDD_MPLABX_WIZARD_START_SECTION: MainLoop *** DO NOT DELETE THIS LINE! ***
// These lines will be replaced by VGDD MPLAB X Wizard with lines for the MainLoop Section
// Don't delete the starting and ending markers!
// VGDD_MPLABX_WIZARD_END_SECTION *** DO NOT DELETE THIS LINE! ***
// </editor-fold>
        /* Maintain state machines of all polled MPLAB Harmony modules. */
        SYS_Tasks();
    }
}

// --------------------------------------------------------------------
// Main functions
// --------------------------------------------------------------------
// <editor-fold defaultstate="collapsed" desc="Generated Code">
// VGDD_MPLABX_WIZARD_START_SECTION: Main *** DO NOT DELETE THIS LINE! ***
// These lines will be replaced by VGDD MPLAB X Wizard with lines for the Main Section
// Don't delete the starting and ending markers!
// VGDD_MPLABX_WIZARD_END_SECTION *** DO NOT DELETE THIS LINE! ***
// </editor-fold>

// --------------------------------------------------------------------
//  Function:
//  bool APP_ObjectMessageCallback(
//                              GFX_GOL_TRANSLATED_ACTION objectMessage,
//                              GFX_GOL_OBJ_HEADER *pObject,
//                              GFX_GOL_MESSAGE *pMessage)
// 
//  Summary:
//      Required application layer function. GFX_GOL_ObjectMessage()
//      function calls this function each time a valid message for the
//      object is received. See GFX_GOL_MessageCallbackSet()
//      documentation in the Graphics Library Help file for details.
// 
//  Parameters:
//      objectMessage - translated message for the object,
//      pObject - pointer to the object,
//      pMessage - pointer to the non-translated, raw GOL message
// 
//  Returns:
//      true  - The message will be processed using default settings
//      false - The message will not be processed by object layer
//              and application may or may not process the message.
// --------------------------------------------------------------------
bool APP_ObjectMessageCallback( GFX_GOL_TRANSLATED_ACTION objectMessage,
                                GFX_GOL_OBJ_HEADER *pObject,
                                GFX_GOL_MESSAGE *pMessage) {

    // The following single call handles messages from all VGDD-generated screens
    return (VGDD_[PROJECT_CLEAN_NAME]_MsgCallback(objectMessage, pObject, pMessage));
}

// --------------------------------------------------------------------
//  Function:
//  bool APP_ObjectDrawCallback(SYS_MODULE_INDEX GFX_INDEX_0)
// 
//  Summary:
//      Required application layer function. GFX_GOL_ObjectListDraw()
//      function calls it each time when object layer drawing is completed.
//      User drawing should be done here. See GFX_GOL_DrawCallbackSet()
//      documentation in the Graphics Library Help file for details.
// 
//  Parameters:
//      None.
// 
//  Returns:
//      true  - When rendering control will be passed back to object layer
//              rendering of the Graphics Library.
//      false - When rendering control stays with the application.
//              Do this when application needs more time to render.
// --------------------------------------------------------------------
bool APP_ObjectDrawCallback(void)
{
    // The following single call handles screenstate changes of all VGDD-generated screens
    return (VGDD_[PROJECT_CLEAN_NAME]_DrawCallback());
}

static enum {
    EXCEP_IRQ = 0, // interrupt
    EXCEP_AdEL = 4, // address error exception (load or ifetch)
    EXCEP_AdES, // address error exception (store)
    EXCEP_IBE, // bus error (ifetch)
    EXCEP_DBE, // bus error (load/store)
    EXCEP_Sys, // syscall
    EXCEP_Bp, // breakpoint
    EXCEP_RI, // reserved instruction
    EXCEP_CpU, // coprocessor unusable
    EXCEP_Overflow, // arithmetic overflow
    EXCEP_Trap, // trap (possible divide by zero)
    EXCEP_IS1 = 16, // implementation specfic 1
    EXCEP_CEU, // CorExtend Unuseable
    EXCEP_C2E // coprocessor 2
} _excep_code;

static unsigned int _epc_code;
static unsigned int _excep_addr;

void _general_exception_handler(void) {
    char *Descr;
    asm volatile("mfc0 %0,$13" : "=r" (_excep_code));
    asm volatile("mfc0 %0,$14" : "=r" (_excep_addr));

    _excep_code = (_excep_code & 0x0000007C) >> 2;

    switch (_excep_code) {
        case EXCEP_IRQ: Descr = "interrupt";
            break;
        case EXCEP_AdEL: Descr = "address error exception (load or ifetch)";
            break;
        case EXCEP_AdES: Descr = "address error exception (store)";
            break;
        case EXCEP_IBE: Descr = "bus error (ifetch)";
            break;
        case EXCEP_DBE: Descr = "bus error (load/store)";
            break;
        case EXCEP_Sys: Descr = "syscall";
            break;
        case EXCEP_Bp: Descr = "breakpoint";
            break;
        case EXCEP_RI: Descr = "reserved instruction";
            break;
        case EXCEP_CpU: Descr = "coprocessor unusable";
            break;
        case EXCEP_Overflow: Descr = "arithmetic overflow";
            break;
        case EXCEP_Trap: Descr = "trap (possible divide by zero)";
            break;
        case EXCEP_IS1: Descr = "implementation specfic 1";
            break;
        case EXCEP_CEU: Descr = "CorExtend Unuseable";
            break;
        case EXCEP_C2E: Descr = "coprocessor 2";
            break;
    }
    //      Uart1TxStringPolled("\r\nGeneral Exception ");
    //      Uart1TxStringPolled(Descr);
    //      Uart1TxStringPolled(" at 0x");
    //      Uart1TxUint32HexPolled(_excep_addr);
    //      Uart1TxStringPolled("\r\n");
    while (1) {
        // Examine _excep_code to identify the type of exception
        // Examine _excep_addr to find the address that caused the exception
    }
}