<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<title>VirtualFab GUIBoard32 - Microchip TCP/IP Stack Demo App</title>
<link href="/mchp.css" rel="stylesheet" type="text/css" />
<script src="/mchp.js" type="text/javascript"></script>
</head>

<body>
<br>
<div id="shadow-one"><div id="shadow-two"><div id="shadow-three"><div id="shadow-four">
<div id="page">

<div id="title">
<div class="right">VirtualFab GUIBoard32&trade; TCP/IP Stack Demo Application</div>
<span id="hello">&nbsp;xxxx</span>
</div>
<div id="menupanel">
<table border="0">
<tr><td align="center">
<a href="http://www.microchip.com" target="_blank">
<img src="/mchp.gif" alt="Microchip Logo" border="0"/>
</a><td></tr>
<tr><td align="center">
<a href="http://virtualfab.it/VGDD" target="_blank">
<img src="/virtfab.png" alt="VirtualFab Logo" border="0"/>
</a><td></tr>
<tr><td align="center">
<div id="menu">
<a href="/index.htm">Main</a>
<a href="/protect/config.htm">Network Settings</a>
<a href="/protect/upload.htm">Upload updates</a>
<a href="/forms.htm">Form Processing</a>
<a href="/protect/auth.htm">Authentication</a>
<a href="/cookies.htm">Cookies</a>
<a href="/email">Send E-mail</a>
<a href="/dyndns">Dynamic DNS</a>
</div>
</td></tr></table>
</div>